
import React from 'react';
import { MeditationStats } from '@/components/progress/types/meditationStats';

interface ReportContentProps {
  meditationStats: MeditationStats;
  userName: string;
}

const ReportContent: React.FC<ReportContentProps> = ({ meditationStats, userName }) => {
  const today = new Date().toLocaleDateString();
  
  return (
    <div className="p-6 bg-white rounded-lg shadow-sm" style={{ width: '800px', minHeight: '600px' }}>
      <div className="flex justify-between items-center mb-6 border-b pb-4">
        <h1 className="text-2xl font-bold text-primary">Meditation Progress Report</h1>
        <div className="text-sm text-muted-foreground">Generated on: {today}</div>
      </div>
      
      <div className="mb-6">
        <h2 className="text-xl font-semibold mb-2">User: {userName}</h2>
        <p className="text-muted-foreground">Summary of your meditation journey</p>
      </div>
      
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-secondary/30 p-4 rounded-md">
          <h3 className="font-medium text-sm text-muted-foreground">Total Sessions</h3>
          <p className="text-2xl font-bold">{meditationStats.totalSessions}</p>
        </div>
        <div className="bg-secondary/30 p-4 rounded-md">
          <h3 className="font-medium text-sm text-muted-foreground">Total Minutes</h3>
          <p className="text-2xl font-bold">{meditationStats.totalMinutes}</p>
        </div>
        <div className="bg-secondary/30 p-4 rounded-md">
          <h3 className="font-medium text-sm text-muted-foreground">Current Streak</h3>
          <p className="text-2xl font-bold">{meditationStats.streak} days</p>
        </div>
      </div>
      
      <div className="mb-6">
        <h3 className="text-lg font-semibold mb-3">Recent Achievements</h3>
        <div className="space-y-2">
          {meditationStats.achievements
            .filter(a => a.unlocked)
            .slice(0, 3)
            .map((achievement, i) => (
              <div key={i} className="flex items-center p-3 bg-secondary/20 rounded-md">
                <div className="mr-3 p-2 bg-primary/10 rounded-full">
                  {achievement.icon && (
                    <span className="text-primary">{achievement.icon}</span>
                  )}
                </div>
                <div>
                  <h4 className="font-medium">{achievement.name}</h4>
                  <p className="text-sm text-muted-foreground">{achievement.description}</p>
                </div>
              </div>
            ))}
        </div>
      </div>
      
      <div className="mb-6">
        <h3 className="text-lg font-semibold mb-3">Focus & Stress Correlation</h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-secondary/30 p-4 rounded-md">
            <h4 className="font-medium text-sm mb-1">Focus Score with Meditation</h4>
            <p className="text-2xl font-bold">{meditationStats.focusCorrelation.withMeditation}%</p>
          </div>
          <div className="bg-secondary/30 p-4 rounded-md">
            <h4 className="font-medium text-sm mb-1">Stress Level Reduction</h4>
            <p className="text-2xl font-bold">
              {meditationStats.moodCorrelation.withMeditation - meditationStats.moodCorrelation.withoutMeditation}%
            </p>
          </div>
        </div>
      </div>
      
      <div className="text-center text-sm text-muted-foreground mt-8 pt-4 border-t">
        <p>Generated by MindfulMe Meditation App</p>
      </div>
    </div>
  );
};

export default ReportContent;
